server:
  port: 8991

spring:
  application:
    name: emp
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://118.31.16.35:3306/db01?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qyl.entity
  configuration:
    map-underscore-to-camel-case: true
