server:
  port: 8992

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: user_route    # 指定路由唯一标识
          uri: lb://user    # 指定路由服务的地址
          predicates:
            - Path=/user/** # 指定路由规则

        - id: emp_route    # 指定路由唯一标识
          uri: lb://emp    # 指定路由服务的地址
          predicates:
            - Path=/emp/** # 指定路由规则
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
