server:
  port: 8989

spring:
  application:
    name: user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  redis:
    host: localhost
    password: 123456
    database: 0
