server:
  port: 8990

spring:
  application:
    name: files
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  resources:
    static-locations: file:${upload.dir}  # 开放展示文件的静态地址

upload.dir: D:\java\javaProject\ems_parent\ems_files\src\main\resources\avatars
